#!/bin/zsh

HOST='alpha.gnu.org'
USER='anonymous'
FILE='grub-0.97-i386-pc.tar.gz'
DISK='floppy.img'

function clean {
        rm -rf bin
        rm -f *.img .bochsout
}

function kernel {
        losetup -d /dev/loop0 \
                > /dev/null 2>&1
        losetup /dev/loop0 $DISK
        mount -text2 /dev/loop0 /mnt
        cp bin/kernel.bin /mnt/boot/
        umount /dev/loop0
        losetup -d /dev/loop0
}

function initrd {
        losetup -d /dev/loop0 \
                > /dev/null 2>&1
        losetup /dev/loop0 $DISK
        mount -text2 /dev/loop0 /mnt
        cp initrd.img /mnt/initrd.img
        umount /dev/loop0
        losetup -d /dev/loop0
}

function update {
        if [ "$1" = "kernel" ]
        then
                kernel
        else
                initrd
        fi
}

function generate {
        gcc -o generator generator.c
        ./generator sample.txt sample.txt another.txt another.txt
        rm -f generator
}

function run {
        losetup -d /dev/loop0
        losetup /dev/loop0 $DISK
        bochs -f .bochsrc
        losetup -d /dev/loop0
}

function make {
        dd if=/dev/zero of=$DISK bs=512 count=2880
        losetup /dev/loop0 $DISK
        mkfs -t ext2 /dev/loop0
        mount -text2 /dev/loop0 /mnt/
        mkdir -p /mnt/boot/grub
        ftp -in $HOST <<FTP
        quote user $USER
        type binary
        cd gnu/grub
        get grub-0.97-i386-pc.tar.gz
        bye
FTP
        tar xf $FILE
        cd `expr substr $FILE 1 17`
        cd boot/grub
        cp stage[12] /mnt/boot/grub
        cd ../../..
        cp menu.lst /mnt/boot/grub/menu.lst
        echo "(fd0) /dev/loop0" > /mnt/boot/grub/device.map
        grub --device-map=/mnt/boot/grub/device.map /dev/loop0 <<GRUB
        root (fd0)
        setup (fd0)
GRUB
        umount /dev/loop0
        losetup -d /dev/loop0
        rm -r grub*
        generate
        update initrd
        update kernel
}


case "$1" in
	clean)
		clean
		;;
	run)
		run
		;;
	generate)
	        generate
                ;;
	update)
	        update $2
                ;;
        make)
                make
                ;;
	esac
exit 0
