#!/bin/zsh

HOST='alpha.gnu.org'
USER='anonymous'
FILE='grub-0.97-i386-pc.tar.gz'
DISK='disk.iso'

function add_grub {
ftp -in $HOST <<FTP
quote user $USER
type binary
cd gnu/grub
get grub-0.97-i386-pc.tar.gz
bye
FTP
tar xf $FILE
cd `expr substr $FILE 1 17`
cd boot/grub
cat stage1 stage2 > $DISK
mv $DISK ../../..
cd ../../..
rm -r grub*
}

function add_pad {
dd if=/dev/zero of=pad bs=1 count=750 \
	> /dev/null 2>&1
cat pad >> $DISK
rm -f pad
}

function add_kernel {
make -C src > /dev/null 2>&1
cat src/kernel >> $DISK \
	> /dev/null 2>&1
}

function clean {
make -C src clean > /dev/null 2>&1
rm -f disk.iso
}

function build {
clean
add_grub
add_pad
add_kernel
}

function run {
sudo bochs -f .bochsrc
}

case "$1" in
	clean)
		clean
		;;
	build)
		build
		;;
	pad)
		add_pad
		;;
	grub)
		add_grub
		;;
	kernel)
		add_kernel
		;;
	run)
		run
		;;
	esac
exit 0
